POST http://localhost:3001/login
accept: application/json
Content-Type: application/json

{"name": "zisui-sukitarou", "password": "passw0rd"}

###

GET http://localhost:3001/find/by/id?userId=01GJ09E8BQCAB6KYA04GGGQSHH
accept: application/json
Content-Type: application/json


###

GET http://localhost:3001/find/by/name?name=zisui-sukitarou
accept: application/json
Content-Type: application/json

###

GET http://localhost:3001/find/by/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUdKMDlFOEJRQ0FCNktZQTA0R0dHUVNISCJ9.7lQrBgjv4_6vUW8BL7upoRZvEUuuYAJXe4eRI2BMT-s