// Code generated by ent, DO NOT EDIT.

package ent

import (
	"zisui-suki-blog/ent/blog"
	"zisui-suki-blog/ent/schema"
	"zisui-suki-blog/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescContent is the schema descriptor for content field.
	blogDescContent := blogFields[2].Descriptor()
	// blog.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	blog.ContentValidator = blogDescContent.Validators[0].(func(string) error)
	// blogDescTitle is the schema descriptor for title field.
	blogDescTitle := blogFields[3].Descriptor()
	// blog.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	blog.TitleValidator = blogDescTitle.Validators[0].(func(string) error)
	// blogDescAbstract is the schema descriptor for abstract field.
	blogDescAbstract := blogFields[4].Descriptor()
	// blog.AbstractValidator is a validator for the "abstract" field. It is called by the builders before save.
	blog.AbstractValidator = blogDescAbstract.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescIcon is the schema descriptor for icon field.
	userDescIcon := userFields[4].Descriptor()
	// user.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	user.IconValidator = userDescIcon.Validators[0].(func(string) error)
}
