// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"zisui-suki-blog/ent/draft"

	"entgo.io/ent/dialect/sql"
)

// Draft is the model entity for the Draft schema.
type Draft struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Abstract holds the value of the "abstract" field.
	Abstract string `json:"abstract,omitempty"`
	// Evaluation holds the value of the "evaluation" field.
	Evaluation uint `json:"evaluation,omitempty"`
	// Status holds the value of the "status" field.
	Status uint `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DraftQuery when eager-loading is set.
	Edges DraftEdges `json:"edges"`
}

// DraftEdges holds the relations/edges for other nodes in the graph.
type DraftEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e DraftEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Draft) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case draft.FieldEvaluation, draft.FieldStatus:
			values[i] = new(sql.NullInt64)
		case draft.FieldID, draft.FieldUserID, draft.FieldContent, draft.FieldTitle, draft.FieldAbstract:
			values[i] = new(sql.NullString)
		case draft.FieldCreatedAt, draft.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Draft", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Draft fields.
func (d *Draft) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case draft.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				d.ID = value.String
			}
		case draft.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				d.UserID = value.String
			}
		case draft.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				d.Content = value.String
			}
		case draft.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				d.Title = value.String
			}
		case draft.FieldAbstract:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field abstract", values[i])
			} else if value.Valid {
				d.Abstract = value.String
			}
		case draft.FieldEvaluation:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field evaluation", values[i])
			} else if value.Valid {
				d.Evaluation = uint(value.Int64)
			}
		case draft.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				d.Status = uint(value.Int64)
			}
		case draft.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				d.CreatedAt = value.Time
			}
		case draft.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				d.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryTags queries the "tags" edge of the Draft entity.
func (d *Draft) QueryTags() *TagQuery {
	return (&DraftClient{config: d.config}).QueryTags(d)
}

// Update returns a builder for updating this Draft.
// Note that you need to call Draft.Unwrap() before calling this method if this Draft
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Draft) Update() *DraftUpdateOne {
	return (&DraftClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Draft entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Draft) Unwrap() *Draft {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Draft is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Draft) String() string {
	var builder strings.Builder
	builder.WriteString("Draft(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("user_id=")
	builder.WriteString(d.UserID)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(d.Content)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(d.Title)
	builder.WriteString(", ")
	builder.WriteString("abstract=")
	builder.WriteString(d.Abstract)
	builder.WriteString(", ")
	builder.WriteString("evaluation=")
	builder.WriteString(fmt.Sprintf("%v", d.Evaluation))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", d.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(d.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(d.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Drafts is a parsable slice of Draft.
type Drafts []*Draft

func (d Drafts) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
