version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: purchase
    ports:
      - 3306:3306
    volumes:
        - db-store:/var/lib/mysql
        - ./script:/docker-entrypoint-initdb.d 
volumes:
  db-store: