POST http://localhost:3002/new/draft
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFHSjA5RThCUUNBQjZLWUEwNEdHR1FTSEgifQ.rtKt4Rdw_tyeVaY-kbpY_SuKomwSejFeFicD2gbAx2w
accept: application/json
Content-Type: application/json

{"userId": "01GJ09E8BQCAB6KYA04GGGQSHH"}

###

POST http://localhost:3002/update/draft
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFHSjA5RThCUUNBQjZLWUEwNEdHR1FTSEgifQ.rtKt4Rdw_tyeVaY-kbpY_SuKomwSejFeFicD2gbAx2w
accept: application/json
Content-Type: application/json

{"draftId": "01GJ4HKM7T9N2YNRT56K11F4DE", "userId": "01GJ09E8BQCAB6KYA04GGGQSHH", "content":"カルボナーラ", "title":"りゅうじのカルボナーラ", "abstract":"おいしい", "evaluation": 9, "status":0, "tags":["パスタ", "カルボナーラ"]}

###

POST http://localhost:3002/update/draft
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFHSjA5RThCUUNBQjZLWUEwNEdHR1FTSEgifQ.rtKt4Rdw_tyeVaY-kbpY_SuKomwSejFeFicD2gbAx2w
accept: application/json
Content-Type: application/json

{"draftId": "01GJ0A87MRWZVY40PPJDX4GMFT", "userId": "01GJ09E8BQCAB6KYA04GGGQSHH", "content":"キノコのパスタ", "title":"きのこの和風パスタ", "abstract":"エリンギとしめじを使ったパスタ", "evaluation": 7, "status":0, "tags":["パスタ", "和風"]}

###

GET http://localhost:3002/find/by/id?blogId=01GG5HVAJY1VV84DFFT083EQ8C
accept: application/json
Content-Type: application/json

###

GET http://localhost:3002/find/by/tag?tagName=パスタ&begin=0&end=1
accept: application/json
Content-Type: application/json

###

GET http://localhost:3002/find/by/userId?userId=01GG4EBVGCF6ZC5NE91KFZ6PH5&begin=0&end=10
accept: application/json
Content-Type: application/json

###

GET http://localhost:3002/find/by/userName?userName=zisui-sukitarou&begin=0&end=10
accept: application/json
Content-Type: application/json

###

GET http://localhost:3002/find/by/tag/userId?tagName=パスタ&userId=01GG4EBVGCF6ZC5NE91KFZ6PH5&begin=0&end=10
accept: application/json
Content-Type: application/json

###

GET http://localhost:3002/find/by/tag/userName?tagName=パスタ&userName=zisui-sukitarou&begin=0&end=10
accept: application/json
Content-Type: application/json


###

POST http://localhost:3002/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFHRzRFQlZHQ0Y2WkM1TkU5MUtGWjZQSDUifQ.KhVnae0iF7uLZWPxfAcC3aIzlAmkiO4jMMTrFb3OgcQ
accept: application/json
Content-Type: application/json

{"blogId": "01GG6SPB7M2ZY2RYCAPENXX02C", "content":"# キノコのパスタ", "title":"きのこの和風パスタ", "abstract":"エリンギと舞茸を使ったパスタ", "evaluation": 4, "status":0, "tags":[]}
